header: false
footer: false

links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/l0s0s"

services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Portainer"
        logo: "assets/tools/docker_icon.png"
        url: "http://losos.cloud:9000"
        target: "_blank" # optional html a tag target attribute

stylesheet:
  - "assets/custom.css"
